namespace EvoS.Framework.Constants.Enums
{
    public enum TurnMessage
    {
        TURN_START,
        BEGIN_RESOLVE,
        MOVEMENT_RESOLVED,
        CLIENTS_RESOLVED_ABILITIES,
        CANCEL_BUTTON_CLICKED,
        SELECTED_ABILITY,
        ABILITY_REQUEST_ACCEPTED,
        ABILITY_REQUEST_REJECTED,
        MOVEMENT_ACCEPTED,
        MOVEMENT_REJECTED,
        RESPAWN,
        PICK_RESPAWN,
        PICKED_RESPAWN,
        MOVE_BUTTON_CLICKED,
        DONE_BUTTON_CLICKED,
        CANCEL_SINGLE_ABILITY,
        CANCEL_MOVEMENT,
        DISCONNECTED,
        NUM_EVENTS,
    }
}
